---
- name: Install systemd-boot
  shell: "bootctl --path=/boot install"
- name: Copy loader config 
  copy:
    src: loader.conf   
    dest: /boot/loader/loader.conf
    force: yes
- name: Copy linux stock kernel config
  copy:
    src: entries/archStock.conf
    dest: /boot/loader/entries/archStock.conf
    force: yes
