---
# Create hooks to prevent Arch from murdering kernel modules on kernel upgrade (so you can for example use a flash drive after upgrading the kernel)
- name: Setup module backup pre hook
  copy:
    src: backup-modules-pre.hook
    dest: /etc/pacman.d/hooks/backup-modules-pre.hook
    force: yes
- name: Setup module backup post hook
  copy:
    src: backup-modules-post.hook
    dest: /etc/pacman.d/hooks/backup-modules-post.hook
    force: yes
