---
- name: Copy logind config
  copy:
    src: logind.conf
    dest: /etc/systemd/logind.conf
    force: yes
- name: Create destination
  file:
      state: directory
      path: /etc/systemd/system/getty@tty1.service.d
      owner: root
      mode: '0755'
- name: Copy getty override config
  copy:
    src: override.conf
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
    force: yes
