---
- name: Copy logind config
  get_url:
    url: https://git.auteiy.me/dmitry/archInstall/raw/master/files/autoLogin/logind.conf
    dest: /etc/systemd/logind.conf
    force: yes
- name: Create destination
  file:
      state: directory
      path: /etc/systemd/system/getty@tty1.service.d
      owner: root
      mode: '0755'
- name: Copy getty override config
  get_url:
    url: https://git.auteiy.me/dmitry/archInstall/raw/master/files/autoLogin/override.conf
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
    force: yes
