---
- name: Copy snapper config 
  copy:
    src: root
    dest: /etc/snapper/configs/root
    force: yes
- name: Enable it
  copy:
    src: snapper
    dest: /etc/conf.d/snapper
    force: yes
- name: Enable cleanup timer
  systemd:
    name: snapper-cleanup.timer
    enabled: yes
- name: Enable timeline timer
  systemd:
    name: snapper-timeline.timer
    enabled: yes
- name: Replace cleanup timer with my own
  copy:
    src: snapper-cleanup.timer
    dest: /etc/systemd/system/timers.target.wants/snapper-cleanup.timer
    force: yes
