---
- name: Make sure english locale is generated everywhere as some apps like Steam have hardcoded paths to it and need it
  notify: "regenerate locales"
  lineinfile:
    path: /etc/locale.gen
    regexp: '^en_US.UTF-8 UTF-8'
    line: 'en_US.UTF-8 UTF-8'
- name: Set /etc/locale.conf to en_US
  notify: "regenerate locales"
  lineinfile:
    path: /etc/locale.conf
    create: yes
    regexp: '^LANG='
    line: 'LANG=en_US.UTF-8'
