---
- name: Update all packages + AUR packages
  shell: yay -Syu a4tech-bloody-driver-git betterlockscreen btrfs-du downgrade dragon-drag-and-drop future-fetch hunspell-ru ix kotatogram-desktop-bin la-capitaine-icon-theme neovim-plug polybar posy-cursors spaceship-prompt-git ttf-apple-emoji ttf-exo-2 ttf-weather-icons ufetch-git vue-cli yadm yay-bin --noconfirm
  become: yes
  become_user: "{{ username }}"
