---
- name: Create destination
  file:
      state: directory
      path: /etc/iwd
      owner: root
      mode: '0755'
- name: Copy iwd config
  copy:
    src: main.conf
    dest: /etc/iwd/main.conf
    force: yes
